FROM mctlab/omnizart:latest

COPY main.py /app/main.py

ENTRYPOINT [ "/usr/bin/python3", "/app/main.py" ]

# COPY main.py /app/main.py
# RUN pip install omnizart
# RUN omnizart
# CMD ["/usr/bin/python3", "/app/main.py"]
